//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsPanel.FastSend_RayganSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FastSend_RayganSMS.FastSendSoap")]
    public interface FastSendSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSendCode", ReplyAction="*")]
        SmsPanel.FastSend_RayganSMS.AutoSendCodeResponse AutoSendCode(SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.AutoSendCodeResponse> AutoSendCodeAsync(SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageWithCode", ReplyAction="*")]
        SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponse SendMessageWithCode(SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageWithCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponse> SendMessageWithCodeAsync(SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSendCode", ReplyAction="*")]
        SmsPanel.FastSend_RayganSMS.CheckSendCodeResponse CheckSendCode(SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.CheckSendCodeResponse> CheckSendCodeAsync(SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSendCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSendCode", Namespace="http://tempuri.org/", Order=0)]
        public SmsPanel.FastSend_RayganSMS.AutoSendCodeRequestBody Body;
        
        public AutoSendCodeRequest() {
        }
        
        public AutoSendCodeRequest(SmsPanel.FastSend_RayganSMS.AutoSendCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSendCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Footer;
        
        public AutoSendCodeRequestBody() {
        }
        
        public AutoSendCodeRequestBody(string Username, string Password, string ReciptionNumber, string Footer) {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Footer = Footer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSendCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSendCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsPanel.FastSend_RayganSMS.AutoSendCodeResponseBody Body;
        
        public AutoSendCodeResponse() {
        }
        
        public AutoSendCodeResponse(SmsPanel.FastSend_RayganSMS.AutoSendCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSendCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long AutoSendCodeResult;
        
        public AutoSendCodeResponseBody() {
        }
        
        public AutoSendCodeResponseBody(long AutoSendCodeResult) {
            this.AutoSendCodeResult = AutoSendCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithCode", Namespace="http://tempuri.org/", Order=0)]
        public SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequestBody Body;
        
        public SendMessageWithCodeRequest() {
        }
        
        public SendMessageWithCodeRequest(SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Code;
        
        public SendMessageWithCodeRequestBody() {
        }
        
        public SendMessageWithCodeRequestBody(string Username, string Password, string ReciptionNumber, string Code) {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponseBody Body;
        
        public SendMessageWithCodeResponse() {
        }
        
        public SendMessageWithCodeResponse(SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendMessageWithCodeResult;
        
        public SendMessageWithCodeResponseBody() {
        }
        
        public SendMessageWithCodeResponseBody(long SendMessageWithCodeResult) {
            this.SendMessageWithCodeResult = SendMessageWithCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSendCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSendCode", Namespace="http://tempuri.org/", Order=0)]
        public SmsPanel.FastSend_RayganSMS.CheckSendCodeRequestBody Body;
        
        public CheckSendCodeRequest() {
        }
        
        public CheckSendCodeRequest(SmsPanel.FastSend_RayganSMS.CheckSendCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSendCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReciptionNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Code;
        
        public CheckSendCodeRequestBody() {
        }
        
        public CheckSendCodeRequestBody(string Username, string Password, string ReciptionNumber, string Code) {
            this.Username = Username;
            this.Password = Password;
            this.ReciptionNumber = ReciptionNumber;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSendCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSendCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsPanel.FastSend_RayganSMS.CheckSendCodeResponseBody Body;
        
        public CheckSendCodeResponse() {
        }
        
        public CheckSendCodeResponse(SmsPanel.FastSend_RayganSMS.CheckSendCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckSendCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckSendCodeResult;
        
        public CheckSendCodeResponseBody() {
        }
        
        public CheckSendCodeResponseBody(bool CheckSendCodeResult) {
            this.CheckSendCodeResult = CheckSendCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FastSendSoapChannel : SmsPanel.FastSend_RayganSMS.FastSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastSendSoapClient : System.ServiceModel.ClientBase<SmsPanel.FastSend_RayganSMS.FastSendSoap>, SmsPanel.FastSend_RayganSMS.FastSendSoap {
        
        public FastSendSoapClient() {
        }
        
        public FastSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FastSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanel.FastSend_RayganSMS.AutoSendCodeResponse SmsPanel.FastSend_RayganSMS.FastSendSoap.AutoSendCode(SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest request) {
            return base.Channel.AutoSendCode(request);
        }
        
        public long AutoSendCode(string Username, string Password, string ReciptionNumber, string Footer) {
            SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest inValue = new SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest();
            inValue.Body = new SmsPanel.FastSend_RayganSMS.AutoSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Footer = Footer;
            SmsPanel.FastSend_RayganSMS.AutoSendCodeResponse retVal = ((SmsPanel.FastSend_RayganSMS.FastSendSoap)(this)).AutoSendCode(inValue);
            return retVal.Body.AutoSendCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.AutoSendCodeResponse> SmsPanel.FastSend_RayganSMS.FastSendSoap.AutoSendCodeAsync(SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest request) {
            return base.Channel.AutoSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.AutoSendCodeResponse> AutoSendCodeAsync(string Username, string Password, string ReciptionNumber, string Footer) {
            SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest inValue = new SmsPanel.FastSend_RayganSMS.AutoSendCodeRequest();
            inValue.Body = new SmsPanel.FastSend_RayganSMS.AutoSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Footer = Footer;
            return ((SmsPanel.FastSend_RayganSMS.FastSendSoap)(this)).AutoSendCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponse SmsPanel.FastSend_RayganSMS.FastSendSoap.SendMessageWithCode(SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest request) {
            return base.Channel.SendMessageWithCode(request);
        }
        
        public long SendMessageWithCode(string Username, string Password, string ReciptionNumber, string Code) {
            SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest inValue = new SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest();
            inValue.Body = new SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponse retVal = ((SmsPanel.FastSend_RayganSMS.FastSendSoap)(this)).SendMessageWithCode(inValue);
            return retVal.Body.SendMessageWithCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponse> SmsPanel.FastSend_RayganSMS.FastSendSoap.SendMessageWithCodeAsync(SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest request) {
            return base.Channel.SendMessageWithCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.SendMessageWithCodeResponse> SendMessageWithCodeAsync(string Username, string Password, string ReciptionNumber, string Code) {
            SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest inValue = new SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequest();
            inValue.Body = new SmsPanel.FastSend_RayganSMS.SendMessageWithCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            return ((SmsPanel.FastSend_RayganSMS.FastSendSoap)(this)).SendMessageWithCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsPanel.FastSend_RayganSMS.CheckSendCodeResponse SmsPanel.FastSend_RayganSMS.FastSendSoap.CheckSendCode(SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest request) {
            return base.Channel.CheckSendCode(request);
        }
        
        public bool CheckSendCode(string Username, string Password, string ReciptionNumber, string Code) {
            SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest inValue = new SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest();
            inValue.Body = new SmsPanel.FastSend_RayganSMS.CheckSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            SmsPanel.FastSend_RayganSMS.CheckSendCodeResponse retVal = ((SmsPanel.FastSend_RayganSMS.FastSendSoap)(this)).CheckSendCode(inValue);
            return retVal.Body.CheckSendCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.CheckSendCodeResponse> SmsPanel.FastSend_RayganSMS.FastSendSoap.CheckSendCodeAsync(SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest request) {
            return base.Channel.CheckSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsPanel.FastSend_RayganSMS.CheckSendCodeResponse> CheckSendCodeAsync(string Username, string Password, string ReciptionNumber, string Code) {
            SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest inValue = new SmsPanel.FastSend_RayganSMS.CheckSendCodeRequest();
            inValue.Body = new SmsPanel.FastSend_RayganSMS.CheckSendCodeRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            inValue.Body.Code = Code;
            return ((SmsPanel.FastSend_RayganSMS.FastSendSoap)(this)).CheckSendCodeAsync(inValue);
        }
    }
}
